# Generated by Django 3.2.7 on 2021-10-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('GoodsID', models.AutoField(primary_key=True, serialize=False, verbose_name='商品号')),
                ('GoodsName', models.CharField(default='', max_length=255, verbose_name='商品名')),
                ('IMG', models.CharField(default='', max_length=255, verbose_name='图片URL')),
                ('Category', models.IntegerField(default=0, max_length=4, verbose_name='商品类型索引')),
                ('OriginalPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品原价')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('Status', models.IntegerField(max_length=1, verbose_name='商品状态')),
                ('Detail', models.TextField(verbose_name='商品描述')),
                ('UID', models.IntegerField(default='', verbose_name='商家ID')),
            ],
            options={
                'db_table': 'Goods',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
