# Generated by Django 3.2.7 on 2021-10-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_auto_20211008_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Category',
            field=models.IntegerField(default=0, verbose_name='商品类型索引'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='Status',
            field=models.IntegerField(verbose_name='商品状态'),
        ),
    ]
