# Generated by Django 3.2.7 on 2021-10-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_auto_20211008_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='用户ID')),
                ('GoodsID', models.IntegerField(verbose_name='商品ID')),
                ('Time', models.DateTimeField(verbose_name='添加时间')),
            ],
            options={
                'db_table': 'ShoppingCar',
            },
        ),
    ]
