# Generated by Django 3.2.7 on 2021-10-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_shoppingcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='用户ID')),
                ('GoodsID', models.IntegerField(verbose_name='商品ID')),
                ('Time', models.DateTimeField(verbose_name='添加时间')),
            ],
            options={
                'db_table': 'UserCollect',
            },
        ),
    ]
