# Generated by Django 3.2.7 on 2021-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_usercollect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcar',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usercollect',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
