# Generated by Django 3.2.7 on 2021-10-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0008_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ExpressNumber',
            field=models.CharField(default='', max_length=25, verbose_name='快递单号'),
        ),
    ]
