# Generated by Django 3.2.7 on 2021-10-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0009_order_expressnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='GuestName',
            field=models.CharField(default='null', max_length=50, verbose_name='收件人姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UName',
            field=models.CharField(default='unnamed', max_length=50, verbose_name='用户名'),
        ),
    ]
