# Generated by Django 3.2.7 on 2021-10-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0010_auto_20211013_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodsPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsID', models.IntegerField(verbose_name='商品ID')),
                ('img', models.FileField(default='/static/img/default.png', upload_to='goodsIMG')),
            ],
            options={
                'db_table': 'goodsPIC',
            },
        ),
        migrations.RemoveField(
            model_name='goods',
            name='IMG',
        ),
        migrations.AddField(
            model_name='user',
            name='userhead',
            field=models.FileField(default='/static/img/default.png', upload_to='userhead'),
        ),
    ]
