# Generated by Django 3.2.7 on 2021-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_auto_20211015_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodspic',
            name='img',
            field=models.ImageField(default='/static/img/default.png', upload_to='goodsIMG'),
        ),
    ]
