# Generated by Django 3.2.7 on 2021-10-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0012_alter_goodspic_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userhead',
        ),
    ]
