# Generated by Django 3.2.7 on 2021-10-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0014_goods_mainpic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '用户订单', 'verbose_name_plural': '用户订单'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcar',
            options={'verbose_name': '用户购物车', 'verbose_name_plural': '用户购物车'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='usercollect',
            options={'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
        migrations.AlterField(
            model_name='goodspic',
            name='img',
            field=models.ImageField(default='/static/img/default.png', upload_to='goodsIMG', verbose_name='图片地址'),
        ),
    ]
