# Generated by Django 3.2.7 on 2021-10-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0015_auto_20211021_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodspic',
            options={'verbose_name': '商品图片', 'verbose_name_plural': '商品图片'},
        ),
    ]
